logging:
  level:
    root: info
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger- %msg%n'
    file: '%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger- %msg%n'
  file:
    name: ./log/analysis/analysis.log
    max-size: 4096MB
    max-history: 7

knife4j:
  #开启增强配置
  enable: true
  #开启生产环境屏蔽
  #production: false

  #开启Swagger的Basic认证功能,默认是false
  basic:
   enable: true
   #Basic认证用户名
   username: root
   #Basic认证密码
   password: root
